#Properties Config file
#Fri May 15 05:49:23 MSK 2026
language=eng
motd=Submarine Server
server-port=19132
white-list=off
max-players=20
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=2
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=udcNkC8Fnh
auto-save=on
view-distance=8
xbox-auth=off
resource-pack=off
force-resource-packs=off
